version: "3.5"
services:
  hoshi:
    container_name: hoshi
    build: .
    depends_on:
      - hoshi_postgres
    networks:
      - hoshinet
    env_file:
      - .env
    environment:
      HOSHI_DATABASE_URL: "postgres://hoshi:docker@hoshi_postgres/hoshi"
  hoshi_postgres:
    container_name: hoshi_postgres
    image: postgres
    networks:
      - hoshinet
    volumes:
      - hoshidata
    environment:
      POSTGRES_USER: hoshi
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: hoshi
networks:
  hoshinet:
    name: hoshinet
volumes:
  hoshidata:
